name: Build and Push /docs to master
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: prepare
        run: |
          git pull
          git switch docs
          git merge main --no-edit -q
          npm ci > /dev/null 2>&1
          git rm docs/*
          npm run build
          git config user.email "github-actions[bot]"
          git config user.name "github-actions[bot]@users.noreply.github.com"
          git add docs > /dev/null 2>&1
          git commit -q --no-verify --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -m "CI push to /docs"
          git push --set-upstream origin docs
