name: Build and Push /docs to master
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare
        run: |
          npm ci
          rm docs/* 
          npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*
