name: Build and Push /docs to master
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare
        run: |
          git checkout docs
          git merge main --no-edit --ff-only -q
          npm ci
          git rm docs/*
          npm run build
          git config user.email "github-actions[bot]"
          git config user.name "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push
