name: Build and Push /docs to master
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare
        run: |
          npm ci
          git rm docs/index.* 
          git restore --staged docs/index.html
      - name: buildIt
        run: |
          npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
